# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: false
        default: 'Sandbox'
      resource_group:
        description: 'Resource Group'     
        required: false
        default: 'dodevza-default'
      location:
        description: 'Location'
        required: false
        default: 'southafricanorth'
      subscription:
        description: 'Subscription'     
        required: false
        default: 'Free Account'
      cluster_name:
        description: 'K8s Clustername'     
        required: false
        default: 'dodevza-k8s-cluster'
      registry_name:
        description: 'ACR Registry name'     
        required: false
        default: 'dodevza-k8s-registry'
      node_count:
        description: 'Node Count'     
        required: false
        default: '1'
      vm_size:
        description: 'Node vm size'     
        required: false
        default: 'A2m_v2'
      load_balancer_sku:
        description: 'Load balancer SKU'     
        required: false
        default: 'Basic'  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  create:
    environment: ${{ github.event.inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: azure/login@v1
        name: Login to azure
        with:
          creds: ${{ secrets.AZ_DEPLOY_CRED }}

      # Create Resource Group If Not exists
      - name: Create Resouce Group
        run: |
          if [ $(az group exists --name "${{ github.event.inputs.resource_group }}") = false ]; then
            az group create --name "${{ github.event.inputs.resource_group }}" -l "${{github.event.inputs.location}}"
          fi
      # Create Cluster
      - name: Run a multi-line script
        run: az aks create -n ${{ github.event.inputs.cluster_name }} -s "${{ github.event.inputs.subscription }}" -g "${{ github.event.inputs.resource_group }}" --node-count ${{ github.event.inputs.node_count }} -s ${{ github.event.inputs.vm_size }} --load-balancer-sku ${{ github.event.inputs.load_balancer_sku }} --generate-ssh-keys --enable-aad --enable-azure-rbac  --yes

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
